### ISSUE TITLE
Crash after trying to use http located iso for boot 

### ISSUE THREAD

**Issue by hsehic** [dmacvicar/terraform-provider-libvirt#252] opened 2017-11-25 22:53 UTC
#  Version Reports:

### Distro  version of host:

``` openSUSE 42.3 ```

### Terraform Version Report
(Provided by running `terraform -v`.)
```Terraform v0.10.7```

### Libvirt version

```
seha@guster:~/Develop/terraform/d47> virsh -c qemu+ssh://root@d47.suse.de/system --version
3.3.0
seha@guster:~/Develop/terraform/d47> 

```

### terraform-provider-libvirt plugin version (git-hash)

``` 
seha@guster:~/Develop/terraform/d47> rpm -qi terraform-provider-libvirt |grep ^Version
Version     : 0.0.0+git20171017.4907902b
seha@guster:~/Develop/terraform/d47> 

```
___
# Description of Issue/Question

### Setup
```
provider "libvirt" {
  uri = "qemu+ssh://root@d47.suse.de/system"
}

// blank 10GB image for net install.
resource "libvirt_volume" "suse-qcow2" {
  name = "suse-qcow2"
  pool = "default"
  format = "qcow2"
  size = 10000000000
}

// set boot order hd, network
resource "libvirt_domain" "domain-suse-qcow2" {
  name = "suse"
  memory = "1024"
  vcpu = 1

  network_interface {
       bridge = "br0"
       mac = "52:54:00:b2:2f:86"
  }

  boot_device {
      dev = [ "cdrom", "hd", "network"]
  }

  disk {
       volume_id = "${libvirt_volume.suse-qcow2.id}"
  }

 disk {
   url = "http://dist.suse.de/install/SLE-15-Installer-Beta3/SLE-15-Installer-DVD-x86_64-Beta3-DVD1.iso"
 }

  graphics {
    type = "vnc"
    listen_type = "address"
  }
}

```
### Steps to Reproduce Issue
```
terraform  init
terraform  get
terraform  plan
terraform  apply
```
___
# Additional Infos:

http://paste.opensuse.org/63008181

**Comment by MalloZup** [comment] 2017-11-26 22:03
Thx, @hsehic for nice report.
If you do 2times terrafom apply , do you still have the issue? Can you reproduce it 10/10 times or issono sporadic? I am asking because i, already saw this error with another tf file. It would be nice if we can reproduce it everytime

**Comment by MalloZup** [comment] 2017-11-27 12:01
@dmacvicar  i tested the setup with a `terraform 11` and worked well same tf file.

maybe do you used some specific calls/feature only avaibles on terraform 11?

**Comment by monstermunchkin** [comment] 2017-11-27 13:51
I can reproduce this in 4907902b. The problem is:
```go
volumeKey := diskMap["volume_id"].(string)
```
This fails with `panic: interface conversion: interface {} is nil, not string` if there's no `volume_id` key. However, this problem is no longer present since we now [check the key](https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_domain.go#L419-L420).

I'm closing this issue since it's no longer valid.

**Closed by monstermunchkin** 2017-11-27 13:51 UTC
