### ISSUE TITLE
Terraform 0.12 update

### ISSUE THREAD

**Issue by alkersan** [dmacvicar/terraform-provider-libvirt#599] opened 2019-05-23 07:46 UTC
## Description of Issue
Terraform reached it's [0.12 release](https://github.com/hashicorp/terraform/releases/tag/v0.12.0).  Would be great to make libvirt provider compatible with it.
___
##  System Information

```
./terraform-provider-libvirt f02e17b6216975e343690e34c73f375b5022da92
Compiled against library: libvirt 5.3.0
Using library: libvirt 5.3.0
Running hypervisor: QEMU 4.0.0
Running against daemon: 5.3.0

Terraform v0.12.0
```
___
## Additional information:

At the moment an attempt to run plan fails with API incompatibility error:
```
~/dev/virt> tf plan
Error: Failed to instantiate provider "libvirt" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

**Comment by MalloZup** [comment] 2019-05-23 09:26
@alkersan  thanks for this issue. I was creating myself an ISSUE for this as reminder.

The release of 0.12 was yesterday announced yesterday, so we heard about that. 
IT will be on our radar to migrate to 0.12 version.

 Currently we will need to investigate what the new version can break in term of backward compatibility (if any breakage), etc..

But yes definitely it something we will do soonish :rocket: :balloon:

**Comment by bartekrutkowski** [comment] 2019-05-28 09:26
@MalloZup Is there any ETA on this? Compatibility with Terraform 0.12 is quite important, as other projects required the upgrade what rendered KVM infrastructure unmanageable for the time being.

**Comment by MalloZup** [comment] 2019-05-28 18:40
@BartoszMilewski we want to release a version in short term with the actual master. After this the terraform v12 should be the fist item of our stack. @dmacvicar cc

**Comment by DMW007** [comment] 2019-06-01 19:15
In the meantime, it's a workaround to use the latest previous 0.11 version (0.11.14) from here: https://releases.hashicorp.com/terraform/0.11.14/

This may be a solutions for beginners like me who just want to play around with Vagrant and libvrt. I can understand that this doesn't solve the problem for users with conflicting other plugins, here you'll need to wait for the announced update.

**Comment by MalloZup** [comment] 2019-06-04 13:03
I'm closing this issue since we plan to do real work and update in this issue https://github.com/dmacvicar/terraform-provider-libvirt/issues/605.

As an update, we have already a PR for doing the updat thx to  @tripledes, the main work will be to see if we have any regression, pkging. Not other feature will be merged into next release.

Thx to everybody :cupid:

**Closed by MalloZup** 2019-06-04 13:03 UTC
Labels: enhancement, need_investigation
