### ISSUE TITLE
Race condition when creating machines?

### ISSUE THREAD

**Issue by abhinavdahiya** [dmacvicar/terraform-provider-libvirt#402] opened 2018-09-07 02:33 UTC
#  Version Reports:

### Distro  version of host:

Fedora 28

### Terraform Version Report

Terraform v0.11.8

### Libvirt version

4.1.0

### terraform-provider-libvirt plugin version (git-hash)

6c9b29437bfee8a24b49a113fbffbbec5f5745cc
___
# Description of Issue/Question

### Setup

```tf
provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_network" "tectonic_net" {
  name = "tectonic"

  mode   = "nat"
  bridge = "tt0"

  domain = "tt.testing"

  addresses = ["192.168.124.0/24"]

  dns = [{
    local_only = true
  }]

  autostart = true
}

locals {
  master_ips = ["192.168.124.11", "192.168.124.12"]
  worker_ips = ["192.168.124.51", "192.168.124.52"]
}

resource "libvirt_domain" "master" {
  count = "2"

  name = "master${count.index}"

  memory = "2048"
  vcpu   = "2"

  console {
    type        = "pty"
    target_port = 0
  }

  network_interface {
    network_id = "${libvirt_network.tectonic_net.id}"
    hostname   = "adahiya-master-${count.index}"
    addresses  = ["${local.master_ips[count.index]}"]
  }
}

resource "libvirt_domain" "worker" {
  count = "2"

  name   = "worker${count.index}"
  memory = "1024"
  vcpu   = "2"

  network_interface {
    network_id = "${libvirt_network.tectonic_net.id}"
    hostname   = "adahiya-worker-${count.index}"
    addresses  = ["${local.worker_ips[count.index]}"]
  }
}

```

### Steps to Reproduce Issue

```console
terraform init
terraform apply
```

Terraform should have created `tectonic` network, 2 master machines and 2 worker machines.

But terraform exists with error:
```console
Error: Error applying plan:

2 error(s) occurred:

* libvirt_domain.worker[0]: 1 error(s) occurred:

* libvirt_domain.worker.0: Error creating libvirt domain: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'tectonic'')
* libvirt_domain.master[0]: 1 error(s) occurred:

* libvirt_domain.master.0: Error creating libvirt domain: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'tectonic'')
```

**Complete output**
```console
Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

libvirt_network.tectonic_net: Creating...
  addresses.#:      "" => "1"
  addresses.0:      "" => "192.168.124.0/24"
  autostart:        "" => "true"
  bridge:           "" => "tt0"
  dns.#:            "" => "1"
  dns.0.local_only: "" => "true"
  domain:           "" => "tt.testing"
  mode:             "" => "nat"
  name:             "" => "tectonic"
libvirt_network.tectonic_net: Creation complete after 5s (ID: 7bcaf736-3b2d-4509-ab1e-7680d6e17fbf)
libvirt_domain.worker[1]: Creating...
  arch:                             "" => "<computed>"
  emulator:                         "" => "<computed>"
  machine:                          "" => "<computed>"
  memory:                           "" => "1024"
  name:                             "" => "worker1"
  network_interface.#:              "" => "1"
  network_interface.0.addresses.#:  "" => "1"
  network_interface.0.addresses.0:  "" => "192.168.124.52"
  network_interface.0.hostname:     "" => "adahiya-worker-1"
  network_interface.0.mac:          "" => "<computed>"
  network_interface.0.network_id:   "" => "7bcaf736-3b2d-4509-ab1e-7680d6e17fbf"
  network_interface.0.network_name: "" => "<computed>"
  qemu_agent:                       "" => "false"
  running:                          "" => "true"
  vcpu:                             "" => "2"
libvirt_domain.worker[0]: Creating...
  arch:                             "" => "<computed>"
  emulator:                         "" => "<computed>"
  machine:                          "" => "<computed>"
  memory:                           "" => "1024"
  name:                             "" => "worker0"
  network_interface.#:              "" => "1"
  network_interface.0.addresses.#:  "" => "1"
  network_interface.0.addresses.0:  "" => "192.168.124.51"
  network_interface.0.hostname:     "" => "adahiya-worker-0"
  network_interface.0.mac:          "" => "<computed>"
  network_interface.0.network_id:   "" => "7bcaf736-3b2d-4509-ab1e-7680d6e17fbf"
  network_interface.0.network_name: "" => "<computed>"
  qemu_agent:                       "" => "false"
  running:                          "" => "true"
  vcpu:                             "" => "2"
libvirt_domain.master[1]: Creating...
  arch:                             "" => "<computed>"
  console.#:                        "" => "1"
  console.0.target_port:            "" => "0"
  console.0.type:                   "" => "pty"
  emulator:                         "" => "<computed>"
  machine:                          "" => "<computed>"
  memory:                           "" => "2048"
  name:                             "" => "master1"
  network_interface.#:              "" => "1"
  network_interface.0.addresses.#:  "" => "1"
  network_interface.0.addresses.0:  "" => "192.168.124.12"
  network_interface.0.hostname:     "" => "adahiya-master-1"
  network_interface.0.mac:          "" => "<computed>"
  network_interface.0.network_id:   "" => "7bcaf736-3b2d-4509-ab1e-7680d6e17fbf"
  network_interface.0.network_name: "" => "<computed>"
  qemu_agent:                       "" => "false"
  running:                          "" => "true"
  vcpu:                             "" => "2"
libvirt_domain.master[0]: Creating...
  arch:                             "" => "<computed>"
  console.#:                        "" => "1"
  console.0.target_port:            "" => "0"
  console.0.type:                   "" => "pty"
  emulator:                         "" => "<computed>"
  machine:                          "" => "<computed>"
  memory:                           "" => "2048"
  name:                             "" => "master0"
  network_interface.#:              "" => "1"
  network_interface.0.addresses.#:  "" => "1"
  network_interface.0.addresses.0:  "" => "192.168.124.11"
  network_interface.0.hostname:     "" => "adahiya-master-0"
  network_interface.0.mac:          "" => "<computed>"
  network_interface.0.network_id:   "" => "7bcaf736-3b2d-4509-ab1e-7680d6e17fbf"
  network_interface.0.network_name: "" => "<computed>"
  qemu_agent:                       "" => "false"
  running:                          "" => "true"
  vcpu:                             "" => "2"
libvirt_domain.worker[1]: Creation complete after 2s (ID: 72dae79b-dc84-4e3a-b6d0-65f478f53038)
libvirt_domain.master[1]: Creation complete after 2s (ID: ed8f694e-3c22-4d36-9e77-63187ee68ba1)

Error: Error applying plan:

2 error(s) occurred:

* libvirt_domain.worker[0]: 1 error(s) occurred:

* libvirt_domain.worker.0: Error creating libvirt domain: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'tectonic'')
* libvirt_domain.master[0]: 1 error(s) occurred:

* libvirt_domain.master.0: Error creating libvirt domain: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'tectonic'')

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by abhinavdahiya** [comment] 2018-09-07 02:36
I suspect it is a race condition because, this main.tf completes to success
```tf
provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_network" "tectonic_net" {
  name = "tectonic"

  mode   = "nat"
  bridge = "tt0"

  domain = "tt.testing"

  addresses = ["192.168.124.0/24"]

  dns = [{
    local_only = true
  }]

  autostart = true
}

locals {
  master_ips = ["192.168.124.11", "192.168.124.12"]
  worker_ips = ["192.168.124.51", "192.168.124.52"]
}

resource "libvirt_domain" "master" {
  count = "2"

  name = "master${count.index}"

  memory = "2048"
  vcpu   = "2"

  console {
    type        = "pty"
    target_port = 0
  }

  network_interface {
    network_id = "${libvirt_network.tectonic_net.id}"
    hostname   = "adahiya-master-${count.index}"
    addresses  = ["${local.master_ips[count.index]}"]
  }
}

resource "libvirt_domain" "worker" {
  count = "2"

  name   = "worker${count.index}"
  memory = "1024"
  vcpu   = "2"

  network_interface {
    network_id = "${libvirt_network.tectonic_net.id}"
    hostname   = "adahiya-worker-${count.index}"
    addresses  = ["${local.worker_ips[count.index]}"]
  }

  depends_on = ["libvirt_domain.master"]
}
```

**Comment by wking** [comment] 2018-09-07 03:50
It's surprising that serializing the domains helps with what seems (from the error message) to be a domain/network race.  Does adding `depends_on = ["libvirt_network.tectonic_net"]` to both master and worker domains have any affect?

**Comment by wking** [comment] 2018-09-07 04:08
> It's surprising that serializing the domains helps with what seems (from the error message) to be a domain/network race.

Ah, the error message is just busted.  Your full log shows `libvirt_network.tectonic_net`'s full creation and the injection of its ID as `network_interface.0.network_id` in all four domains.

**Comment by wking** [comment] 2018-09-07 04:31
I can not reproduce this on RHEL 7.5's 3.10.0-891.el7.x86_64 kernel with Terraform 0.11.7, libvirt 3.9.0, QEMU 2.9.0, and terraform-provider-libvirt 7e52bbeb0 or 6c9b29437.  I also failed to reproduce this with Terraform 0.11.8 and terraform-provider-libvirt 6c9b29437.  Maybe it's a kernel/libvirt/QEMU bug?

**Comment by MalloZup** [comment] 2018-09-07 07:13
hi @wking  @abhinavdahiya  thx for reporting.
@abhinavdahiya can you attach 

`TF_LOG=debug terraform apply`

@wking  for libvirt logs https://wiki.libvirt.org/page/DebugLogs. ( could be interesting if you find something there with libvirt.logs)

Just looking for your logs to me looks a race condition, namely that the network is created but *notyet* for the domains which don't see it. but i'm curious to see the logs of terraform debug

tia

**Comment by steveeJ** [comment] 2018-09-07 14:09
I'm able to reproduce it in about 9/10 cases.

Running this on:
```
# system
Linux steveej-laptop 4.17.19 #1-NixOS SMP Fri Aug 24 11:07:17 UTC 2018 x86_64 GNU/Linux

# libvirt
Compiled against library: libvirt 3.10.0
Using library: libvirt 3.10.0
Using API: QEMU 3.10.0
Running hypervisor: QEMU 2.11.2
```

[Here's are the terraform and libvirt logs][tflogs].

[tflogs]: https://gist.github.com/steveeJ/6140b8a68c449f0c860e891d3c347c69

**Comment by wking** [comment] 2018-09-07 14:32
[Here][1] is the libvirt bug for "Hash operation not allowed during iteration".

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1576464

**Comment by MalloZup** [comment] 2018-09-07 14:43
@wking @steveeJ thank you for infos.

@wking  yeah this is really a know and annoying bug on libvirt side. I have also encountered many times, and we are also impacted in other projects... :notes: 

@abhinavdahiya  i don't think that reverting would help in that case but (from my pov).

The actual solution is to upgrade the libvirt pkg

**Comment by wking** [comment] 2018-09-07 16:49
I'm running RHEL's libvirt 3.9.0 14.el7_5.6, which has a patch:

```console
$ rpm -q --changelog libvirt | head -n3
* Tue Jun 05 2018 Jiri Denemark <jdenemar@redhat.com> - 3.9.0-14.el7_5.6
- logging: Don't inhibit shutdown in system daemon (rhbz#1573268)
- util: don't check for parallel iteration in hash-related functions (rhbz#1581364)
```

[rhbz#1581364][1] is a backport to RHEL 7.5 of the [rhbz#1576464][2] I linked [earlier][3].  The upstream commit fixing this (linked from [rhbz#1576464][2]) is [4d7384eb][4], which punts serialization up to the callers.  I'm not sure if the issue we're seeing here is because:

a. The old check (before libvirt/libvirt@4d7384eb) was overly strict.
b. Folks seeing problems are running versions of libvirt with *internal* racy `virhash.c` consumers.
c. Folks seeing problems are running libvirt *callers* with racy `virhash.c` consumers.

(a) and (b) would be addressable by patching libvirt.  (c) might be an issue with this repository.

@MalloZup, does that make sense?  Do you know which case applies?

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1581364
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1576464
[3]: https://github.com/dmacvicar/terraform-provider-libvirt/issues/402#issuecomment-419458319
[4]: https://libvirt.org/git/?p=libvirt.git;a=commit;h=4d7384eb9ddef2008cb0cc165eb808f74bc83d6b

**Comment by MalloZup** [comment] 2018-09-10 07:38
@wking  thank you for your precise comment.

From my pov is a great news the fact you cannot reproduce with latest libvirt (https://github.com/dmacvicar/terraform-provider-libvirt/issues/402#issuecomment-419319517)

i plan to update to next libvirt-devel version containing that patch so i can verify if we have other issues.

To me i would 98.99%  ( ,0.99 is for com purposes :smile: ) exclude the (c) hypothesis because the locking mechanism and race conditions due to repository:

the mutex mechanism is working well on the pool level when we create volumes.

https://github.com/dmacvicar/terraform-provider-libvirt/blob/676b5a3fec75664990e5a91f24859f35becdee6a/libvirt/resource_libvirt_volume.go#L80

and we lock always before refreshing pools.

https://github.com/dmacvicar/terraform-provider-libvirt/blob/676b5a3fec75664990e5a91f24859f35becdee6a/libvirt/resource_libvirt_volume.go#L91

So to me once the libvirt version is higher the pb should disappear. ( i will test this week this).

For any info/question feel free to ping me and thanks for your collaboration and infos :+1:

**Comment by steveeJ** [comment] 2018-09-10 14:53
@wking 

> I'm not sure if the issue we're seeing here is because:
> 
> a. The old check (before libvirt/libvirt@4d7384e) was overly strict.
> b. Folks seeing problems are running versions of libvirt with internal racy virhash.c consumers.
> c. Folks seeing problems are running libvirt callers with racy virhash.c consumers.

According to [Bug 1581364](https://bugzilla.redhat.com/show_bug.cgi?id=1581364) which you linked as the fix, it says:

> Prior to this update, guest virtual machine actions that use a python library in some cases failed and "Hash operation not allowed during iteration" error messages were logged. Several redundant thread access checks have been removed, and the problem no longer occurs.

which reads to me as case (a), and I'm not sure if (b) is also the case because the callchain isn't obvious to me yet. I'm wondering if there's anything we can do to diminish the problem on the client side.

**Comment by wking** [comment] 2018-09-11 03:56
> I'm wondering if there's anything we can do to diminish the problem on the client side.

openshift/installer#226 is a client-side workaround (using the `depends_on` approach @abhinavdahiya floated [earlier][1].  With the libvirt patch out for months, the easiest approach is probably "bump your libvirt to pick up the (backported) patch."

[1]: https://github.com/dmacvicar/terraform-provider-libvirt/issues/402#issuecomment-419302152

**Comment by MalloZup** [comment] 2018-12-15 09:39
Closing since cleared. Thx all contributors and Linux lover, no matter which distro.

**Closed by MalloZup** 2018-12-15 09:39 UTC
Labels: libvirt_bug
