### ISSUE TITLE
Volume creation error with logical pool based on LVM Volume Group

### ISSUE THREAD

**Issue by vjdhama** [dmacvicar/terraform-provider-libvirt#586] opened 2019-04-11 06:36 UTC
### Linux distribution

``` Ubuntu 18.04 ```

### Terraform version

```sh
Terraform v0.11.13
+ provider.libvirt (unversioned)
+ provider.template v2.1.0
```

### Provider and libvirt versions

```sh
terraform-provider-libvirt 0.5.1
Compiled against library: libvirt 4.0.0
Using library: libvirt 4.0.0
Running hypervisor: QEMU 2.11.1
Running against daemon: 4.0.0
```

___

## Checklist

- [x] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

### Setup

```
resource "libvirt_volume" "base_volume" {
  name   = "base_ubuntu"
  source = "/home/admin/virt/images/ubuntu-base3.raw"
}

resource "libvirt_volume" "vm_volume" {
  name           	= "i-test-lvm-01"
  pool           	= "default"
  format 		= "raw"
  base_volume_id 	= "${libvirt_volume.base_volume.id}"
  size 			= "10485760000"
}
```

The default `pool` is Volume Group.

Pool xml :

```
<pool type='logical'>
  <name>default</name>
  <uuid>44404263-74c1-47ec-b30b-99d3a286f1c6</uuid>
  <capacity unit='bytes'>3598909964288</capacity>
  <allocation unit='bytes'>10745806848</allocation>
  <available unit='bytes'>3588164157440</available>
  <source>
    <device path='/dev/sdb1'/>
    <name>default</name>
    <format type='lvm2'/>
  </source>
  <target>
    <path>/dev/default</path>
  </target>
</pool>
 ```

### Error

```
libvirt_volume.base_volume: Creating...
  format: "" => "<computed>"
  name:   "" => "base_ubuntu"
  pool:   "" => "default"
  size:   "" => "<computed>"
  source: "" => "/home/admin/virt/images/ubuntu-base3.raw"
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt: 2019/04/11 13:50:02 Image /home/svr-admin/virt/images/ubuntu-base3.raw image is: 16106127360 bytes
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt: 2019/04/11 13:50:02 [DEBUG] Generated XML for libvirt volume:
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:   <volume>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:       <name>base_ubuntu</name>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:       <capacity unit="B">0</capacity>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:       <target>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:           <format type="qcow2"></format>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:           <permissions>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:               <mode>644</mode>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:           </permissions>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:       </target>
2019-04-11T13:50:02.726+0700 [DEBUG] plugin.terraform-provider-libvirt:   </volume>
2019/04/11 13:50:02 [TRACE] root: eval: *terraform.EvalWriteState
2019/04/11 13:50:02 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/04/11 13:50:02 [TRACE] root: eval: *terraform.EvalIf
2019/04/11 13:50:02 [TRACE] root: eval: *terraform.EvalWriteState
2019/04/11 13:50:02 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/04/11 13:50:02 [TRACE] root: eval: *terraform.EvalApplyPost
2019/04/11 13:50:02 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* libvirt_volume.base_volume: Error creating libvirt volume: virError(Code=3, Domain=18, Message='this function is not supported by the connection driver: volume capacity required for this storage pool')
2019/04/11 13:50:02 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* libvirt_volume.base_volume: Error creating libvirt volume: virError(Code=3, Domain=18, Message='this function is not supported by the connection driver: volume capacity required for this storage pool')
2019/04/11 13:50:02 [TRACE] [walkApply] Exiting eval tree: libvirt_volume.base_volume
2019/04/11 13:50:02 [TRACE] dag/walk: upstream errored, not walking "libvirt_volume.vm_volume"
2019/04/11 13:50:02 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/04/11 13:50:02 [TRACE] dag/walk: upstream errored, not walking "provider.libvirt (close)"
2019/04/11 13:50:02 [TRACE] dag/walk: upstream errored, not walking "root"
2019/04/11 13:50:02 [TRACE] Preserving existing state lineage "deedaedc-7a7b-6d54-3ed2-26f23323e576"
2019/04/11 13:50:02 [TRACE] Preserving existing state lineage "deedaedc-7a7b-6d54-3ed2-26f23323e576"
2019/04/11 13:50:02 [TRACE] Preserving existing state lineage "deedaedc-7a7b-6d54-3ed2-26f23323e576"
2019/04/11 13:50:02 [TRACE] Preserving existing state lineage "deedaedc-7a7b-6d54-3ed2-26f23323e576"
2019/04/11 13:50:02 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: Error applying plan:

1 error(s) occurred:

* libvirt_volume.base_volume: 1 error(s) occurred:

2019-04-11T13:50:02.739+0700 [DEBUG] plugin.terraform-provider-libvirt: 2019/04/11 13:50:02 [ERR] plugin: plugin server: accept unix /tmp/plugin524676884: use of closed network connection
2019-04-11T13:50:02.739+0700 [DEBUG] plugin.terraform-provider-libvirt: 2019/04/11 13:50:02 [DEBUG] cleaning up connection for URI: qemu:///system
2019-04-11T13:50:02.739+0700 [DEBUG] plugin.terraform-provider-template_v2.1.0_x4: 2019/04/11 13:50:02 [ERR] plugin: plugin server: accept unix /tmp/plugin499886032: use of closed network connection
* libvirt_volume.base_volume: Error creating libvirt volume: virError(Code=3, Domain=18, Message='this function is not supported by the connection driver: volume capacity required for this storage pool')

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce Issue

1. Create pool using above xml.
2. Convert qcow2 image to raw image using : `qemu-img convert -f qcow2 -O raw /home/admin/virt/images/ubuntu-base3.qcow2 /home/admin/virt/images/ubuntu-base3.raw`
3. `terraform apply` with above terraform config

Using `qcow2` base image also doesn't work.

Relevent docs: https://libvirt.org/storage.html#StorageBackendLogical
___
## Additional information:

libvirtd.conf

```
# Disable TLS
listen_tls = 0
# Enable TCP port
listen_tcp = 1
# Add TCP port
tcp_port = "16509"
# Setup libvirt socket group
unix_sock_group = "libvirt"
# Setup libvirt socket permissions
unix_sock_ro_perms = "0777"
unix_sock_rw_perms = "0770"
# Setup libvirt auth
auth_unix_ro = "none"
auth_unix_rw = "none"
# Disable TCP auth
auth_tcp = "none"
# Enable auth log
audit_logging = 1
```

**Comment by Cicero-Zhao** [comment] 2019-05-16 09:00
I meet same question, and find the root cause is it didn't resolve image file correctly, and generated wrong vol create xml string.

Let me put my configuration files, (actually, almost same with @vjdhama 

1. tf configuration file:

```
resource "libvirt_volume" "centos7-image" {
  name = "rong_test"
  pool = "pri"
  source = "http://10.41.8.224/images/CentOS-7-x86_64-GenericCloud.raw"
}
```

2. the vol create xml string:
```
[DEBUG] plugin.terraform-provider-libvirt: 2019/05/16 01:46:37 [DEBUG] Generated XML for libvirt volume:
[DEBUG] plugin.terraform-provider-libvirt:   <volume>
[DEBUG] plugin.terraform-provider-libvirt:       <name>rong_test</name>
[DEBUG] plugin.terraform-provider-libvirt:       <capacity unit="B">0</capacity>
[DEBUG] plugin.terraform-provider-libvirt:       <target>
[DEBUG] plugin.terraform-provider-libvirt:           <format type="qcow2"></format>
[DEBUG] plugin.terraform-provider-libvirt:           <permissions>
[DEBUG] plugin.terraform-provider-libvirt:               <mode>644</mode>
[DEBUG] plugin.terraform-provider-libvirt:           </permissions>
[DEBUG] plugin.terraform-provider-libvirt:       </target>
[DEBUG] plugin.terraform-provider-libvirt:   </volume>
```

3. We can see the problems here
3.1 capacity = 0B
3.2 the type = qcow2 although I passed a raw image

4. image information
```
/var/www/html/images$ qemu-img info CentOS-7-x86_64-GenericCloud.raw 
image: CentOS-7-x86_64-GenericCloud.raw
file format: raw
virtual size: 8.0G (8589934592 bytes)
disk size: 881M
```

So, the things became easy, we need to parse correct image information and pass to volume create function.

**Comment by Cicero-Zhao** [comment] 2019-05-16 09:08
Hm... looks like @vjdhama  has pasted the debug log and it has shown the root cause.. will check how to fix for my own environment.. please ignore my last post if it create noise...

**Comment by Cicero-Zhao** [comment] 2019-05-16 09:44
I met same issue, git clone the latest code, compile, it works.

**Comment by zeenix** [comment] 2019-07-09 16:13
Based on latest commit, let's close this one too. @MalloZup

**Closed** 2019-07-09 16:35 UTC
Labels: need_investigation
