### ISSUE TITLE
 Timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)

### ISSUE THREAD

**Issue by jcayouette** [dmacvicar/terraform-provider-libvirt#246] opened 2017-11-21 14:55 UTC
#  Version Reports:

### Distro  version of host:

``` openSUSE 42.3```

### Terraform Version Report

```Terraform v0.10.7```

### Libvirt version

```3.3.0```

### terraform-provider-libvirt plugin version (git-hash)

```terraform-provider-libvirt-0.0.0+git20171027.feec1d19-1.2.x86_64```
___
# Description of Issue/Question
Running sumaform with a typical setup, br0 with the following settings.
```
### Setup
provider "libvirt" {
  uri = "qemu:///system"
}

module "base" {
  source = "./modules/libvirt/base"

  cc_username = "UC7"
  cc_password = "SUPER_SECRET_PASSWORD"

  // optional parameters with defaults below
  pool = "suma"
  network_name = ""
  bridge = "br0"
  name_prefix = "doctest-"
  // timezone = "Europe/Berlin"
}

module "suma3pg" {
  source = "./modules/libvirt/suse_manager"
  base_configuration = "${module.base.configuration}"

  name = "suma3pg"
  version = "head"
  // see modules/libvirt/suse_manager/variables.tf for possible values
}

module "galaxy-proxy_1" {
  source = "./modules/libvirt/suse_manager_proxy"
  base_configuration = "${module.base.configuration}"

  name = "galaxy-proxy_1"
  version = "head"
  server_configuration = "${module.suma3pg.configuration}"
}

module "minion-sles12sp2" {
  source = "./modules/libvirt/minion"
  base_configuration = "${module.base.configuration}"

  name = "minsles12sp2"
  image = "sles12sp2"
  server_configuration = "${module.suma3pg.configuration}"
  count = 1
  // see modules/libvirt/minion/variables.tf for possible values
}

module "client-sles12sp1" {
  source = "./modules/libvirt/client"
  base_configuration = "${module.base.configuration}"

  name = "clientsles12sp1"
  image = "sles12sp1"
  server_configuration = "${module.suma3pg.configuration}"
  count = 1
  // see modules/libvirt/minion/variables.tf for possible values
}
```
### Steps to Reproduce Issue

terraform plan output:
```Terraform will perform the following actions:

  + module.base.libvirt_volume.volumes[0]
2017/11/21 15:43:35 [DEBUG] plugin: waiting for all plugin processes to complete...
      id:                                 <computed>
      name:                               "doctest-centos7"
      pool:                               "suma"
      size:                               <computed>
      source:                             "http://w3.nue.suse.com/~smoioli/sumaform-images/centos7_v2.qcow2"

  + module.base.libvirt_volume.volumes[1]
      id:                                 <computed>
      name:                               "doctest-opensuse422"
      pool:                               "suma"
      size:                               <computed>
      source:                             "http://download.opensuse.org/repositories/home:/SilvioMoioli:/Terraform:/Images/images/opensuse422.x86_64.qcow2"

  + module.base.libvirt_volume.volumes[2]
      id:                                 <computed>
      name:                               "doctest-sles11sp3"
      pool:                               "suma"
      size:                               <computed>
      source:                             "http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles11sp3.x86_64.qcow2"

  + module.base.libvirt_volume.volumes[3]
      id:                                 <computed>
      name:                               "doctest-sles11sp4"
      pool:                               "suma"
      size:                               <computed>
2017-11-21T15:43:35.551+0100 [DEBUG] plugin.terraform: file-provisioner (internal) 2017/11/21 15:43:35 [DEBUG] plugin: waiting for all plugin processes to complete...
2017-11-21T15:43:35.552+0100 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2017/11/21 15:43:35 [DEBUG] plugin: waiting for all plugin processes to complete...
      source:                             "http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles11sp4.x86_64.qcow2"

  + module.base.libvirt_volume.volumes[4]
      id:                                 <computed>
      name:                               "doctest-sles12"
      pool:                               "suma"
      size:                               <computed>
      source:                             "http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12.x86_64.qcow2"

  + module.base.libvirt_volume.volumes[5]
      id:                                 <computed>
      name:                               "doctest-sles12sp1"
      pool:                               "suma"
      size:                               <computed>
      source:                             "http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp1.x86_64.qcow2"

  + module.base.libvirt_volume.volumes[6]
      id:                                 <computed>
      name:                               "doctest-sles12sp2"
      pool:                               "suma"
      size:                               <computed>
2017-11-21T15:43:35.554+0100 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform
2017-11-21T15:43:35.554+0100 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform
2017-11-21T15:43:35.554+0100 [DEBUG] plugin: plugin process exited: path=/usr/bin/terraform-provider-libvirt
      source:                             "http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp2.x86_64.qcow2"

  + module.base.libvirt_volume.volumes[7]
      id:                                 <computed>
      name:                               "doctest-sles12sp3"
      pool:                               "suma"
      size:                               <computed>
      source:                             "http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp3.x86_64.qcow2"

  + module.client-sles12sp1.module.client.libvirt_domain.domain
      id:                                 <computed>
      arch:                               "x86_64"
      disk.#:                             <computed>
      emulator:                           "/usr/bin/qemu-system-x86_64"
      machine:                            "pc"
      memory:                             "512"
      name:                               "doctest-clientsles12sp1"
      network_interface.#:                "1"
      network_interface.0.addresses.#:    <computed>
      network_interface.0.bridge:         "br0"
      network_interface.0.hostname:       <computed>
      network_interface.0.mac:            <computed>
      network_interface.0.network_id:     <computed>
      network_interface.0.network_name:   <computed>
      network_interface.0.wait_for_lease: "true"
      running:                            "true"
      vcpu:                               "1"

  + module.client-sles12sp1.module.client.libvirt_volume.main_disk
      id:                                 <computed>
      base_volume_name:                   "doctest-sles12sp1"
      name:                               "doctest-clientsles12sp1-main-disk"
      pool:                               "suma"
      size:                               <computed>

  + module.galaxy-proxy_1.module.suse_manager_proxy.libvirt_domain.domain
      id:                                 <computed>
      arch:                               "x86_64"
      disk.#:                             <computed>
      emulator:                           "/usr/bin/qemu-system-x86_64"
      machine:                            "pc"
      memory:                             "1024"
      name:                               "doctest-galaxy-proxy_1"
      network_interface.#:                "1"
      network_interface.0.addresses.#:    <computed>
      network_interface.0.bridge:         "br0"
      network_interface.0.hostname:       <computed>
      network_interface.0.mac:            <computed>
      network_interface.0.network_id:     <computed>
      network_interface.0.network_name:   <computed>
      network_interface.0.wait_for_lease: "true"
      running:                            "true"
      vcpu:                               "1"

  + module.galaxy-proxy_1.module.suse_manager_proxy.libvirt_volume.main_disk
      id:                                 <computed>
      base_volume_name:                   "doctest-sles12sp2"
      name:                               "doctest-galaxy-proxy_1-main-disk"
      pool:                               "suma"
      size:                               <computed>

  + module.minion-sles12sp2.module.minion.libvirt_domain.domain
      id:                                 <computed>
      arch:                               "x86_64"
      disk.#:                             <computed>
      emulator:                           "/usr/bin/qemu-system-x86_64"
      machine:                            "pc"
      memory:                             "512"
      name:                               "doctest-minsles12sp2"
      network_interface.#:                "1"
      network_interface.0.addresses.#:    <computed>
      network_interface.0.bridge:         "br0"
      network_interface.0.hostname:       <computed>
      network_interface.0.mac:            <computed>
      network_interface.0.network_id:     <computed>
      network_interface.0.network_name:   <computed>
      network_interface.0.wait_for_lease: "true"
      running:                            "true"
      vcpu:                               "1"

  + module.minion-sles12sp2.module.minion.libvirt_volume.main_disk
      id:                                 <computed>
      base_volume_name:                   "doctest-sles12sp2"
      name:                               "doctest-minsles12sp2-main-disk"
      pool:                               "suma"
      size:                               <computed>

  + module.suma3pg.module.suse_manager.libvirt_domain.domain
      id:                                 <computed>
      arch:                               "x86_64"
      disk.#:                             <computed>
      emulator:                           "/usr/bin/qemu-system-x86_64"
      machine:                            "pc"
      memory:                             "4096"
      name:                               "doctest-suma3pg"
      network_interface.#:                "1"
      network_interface.0.addresses.#:    <computed>
      network_interface.0.bridge:         "br0"
      network_interface.0.hostname:       <computed>
      network_interface.0.mac:            <computed>
      network_interface.0.network_id:     <computed>
      network_interface.0.network_name:   <computed>
      network_interface.0.wait_for_lease: "true"
      running:                            "true"
      vcpu:                               "2"

  + module.suma3pg.module.suse_manager.libvirt_volume.main_disk
      id:                                 <computed>
      base_volume_name:                   "doctest-sles12sp3"
      name:                               "doctest-suma3pg-main-disk"
      pool:                               "suma"
      size:                               <computed>


Plan: 16 to add, 0 to change, 0 to destroy.
```

### Terraform Apply Output
```
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [DEBUG] Parsed response {Interfaces:[{Name:lo Hwaddr:00:00:00:00:00:00 IpAddresses:[{Type:ipv4 Address:127.0.0.1 Prefix:8} {Type:ipv6 Address:::1 Prefix:128}]} {Name:eth0 Hwaddr:52:13:53:b5:bc:07 IpAddresses:[{Type:ipv6 Address:2620:113:80c0:8080:10:160:68:42 Prefix:64} {Type:ipv6 Address:2620:113:80c0:8080:5013:53ff:feb5:bc07 Prefix:64} {Type:ipv6 Address:fe80::5013:53ff:feb5:bc07 Prefix:64}]}]}
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [DEBUG] Interfaces obtained via qemu-agent: []
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [DEBUG] no interfaces could be obtained with qemu-agent: falling back to the libvirt API
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [DEBUG] Interfaces info obtained with libvirt API:
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: ([]libvirt.DomainInterface) {
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: }
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [DEBUG] ifaces with addresses: []
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [DEBUG] 52:13:53:B5:BC:07 doesn't have IP address(es) yet...
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [DEBUG] IP address not found for iface=52:13:53:B5:BC:07: will try in a while
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [TRACE] Waiting 10s before next try
2017-11-21T15:53:02.412+0100 [DEBUG] plugin.terraform-provider-libvirt: 2017/11/21 15:53:02 [DEBUG] wait-for-leases was successful
2017/11/21 15:53:02 [ERROR] root.suma3pg.suse_manager: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* libvirt_domain.domain: timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)
2017/11/21 15:53:02 [ERROR] root.suma3pg.suse_manager: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* libvirt_domain.domain: timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)
2017/11/21 15:53:02 [DEBUG] plugin: waiting for all plugin processes to complete...
Error applying plan:

1 error(s) occurred:

* module.suma3pg.module.suse_manager.libvirt_domain.domain: 1 error(s) occurred:

* libvirt_domain.domain: timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)


___


# Additional Infos:
Firewall = disabled
Apparmor = disabled
IPv6 = disabled

**Comment by jcayouette** [comment] 2017-11-22 09:22
I just discovered there is a rogue vnet0 assigned to br0 which conflicts with the actual br0 assigned to my physical device em1. Removed and disabled vnet0 with `ip link delete vnet0`. I have no idea where this came from. Ill update on status.

**Comment by jcayouette** [comment] 2017-11-22 09:47
The issue still persists. :(

**Comment by MalloZup** [comment] 2017-11-30 10:35
@jcayouette  afaik to me this is fixed to the latest version, you should take the latest rpm from the repo (see readme) and try to reproduce, but we fixed it by a pr that got merged

**Comment by MalloZup** [comment] 2017-12-07 08:30
@jcayouette to me is fixed. Can you install the latest plugin and verify?

**Comment by aboe76** [comment] 2018-04-06 21:41
still an issue with
```
Repository     : Virtualization:containers (openSUSE_Tumbleweed)              
Name           : terraform-provider-libvirt                                   
Version        : 0.0.0+git20180220.f2cef405-1.6    
```

```
Error: Error applying plan:

1 error(s) occurred:

* libvirt_domain.domain: 1 error(s) occurred:

* libvirt_domain.domain: timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)

```

**Comment by MalloZup** [comment] 2018-04-18 07:54
i can confirm, i had recently same issue. thx @aboe76 

@inercia  feel free to have a look once you have some free time

**Comment by inercia** [comment] 2018-04-18 08:37
When using a NATed network, libvirt starts its own DHCP server and the terraform-libvirt provider can query that server about the IPs for a domain. However, no DHCP server is started when using a bridge (like in this case), so the terraform libvirt provider cannot get the IP addresses. In this case, the provider falls back to asking a running `qemu-agent` in the domain and, if no `qemu-agent` is running, the IP addresses collection will timeout...

So I guess we should document all these things, right? :-)

**Comment by MalloZup** [comment] 2018-04-18 08:39
yop we can document and close it

From my case, i add this issue with a sle15 image so it was not related  to a bug and the error was correct because the sle15 img missed some terraform dep. pkg needed to access it

**Comment by MalloZup** [comment] 2018-07-10 10:08
@inercia as far i understood is more a user documentation problem then a bug, can you confirm that?.

If so is just a matter of doing some documentation and we are done. Tia

**Closed** 2018-08-23 18:46 UTC
Labels: needinfo
