### ISSUE TITLE
error starting VM with a second disk 

### ISSUE THREAD

**Issue by fisabelle** [dmacvicar/terraform-provider-libvirt#19] opened 2016-05-10 20:20 UTC
Whenever I start a VM with more than 1 disk attached I get:

* libvirt_domain.centos6_vm1_domain: Error crearing libvirt domain: [Code-27] [Domain-20] XML error: target 'sda' duplicated for disk sources '/home/vmstore/images/centos6_vm1disk_44_data' and '/home/vmstore/images/centos6_vm1disk_44'

using libvirt-daemon-kvm-1.3.0-1.el7.x86_64

module.vm_dbs_redundant.libvirt_domain.centos6_vm1_domain: Creating...
  disk.#:                      "" => "2"
  disk.0.volume_id:            "" => "/home/vmstore/images/centos6_vm1disk_44"
  disk.1.volume_id:            "" => "/home/vmstore/images/centos6_vm1disk_44_data"
  memory:                      "" => "6144"
  name:                        "" => "centos6_vm_domain_44"
  network_interface.#:         "" => "1"
  network_interface.0.mac:     "" => "52:54:00:A1:A3:44"
  network_interface.0.network: "" => "host-bridge2"
  vcpu:                        "" => "2"

Is that working properly on your side ?

**Comment by dmacvicar** [comment] 2016-05-10 22:26
This is a duplicate of issue #14 isn't it?

@fisabelle Can you test with a current checkout? Reopen if master does not fix it for you.

BTW, is it helpful if I start publishing binary builds?

**Closed by dmacvicar** 2016-05-10 22:26 UTC
Labels: duplicate

**Comment by fisabelle** [comment] 2016-05-11 00:18
Thanks @dmacvicar it works with the latest from master. Sorry about the duplicate.
I don't know if a binary is needed. I don't mind rebuilding. But some official "release" when a few interesting bug fix make their way could be nice.

**Comment by dmacvicar** [comment] 2016-05-11 07:13
@fisabelle I think only one important feature is missing which is the ip address so that the provisioners work automatically. Lets do a 0.1 release after I get that done.
