### ISSUE TITLE
libvirt_volume: Error while uploading source os-image.qcow2: unexpected EOF

### ISSUE THREAD

**Issue by ayaseen** [dmacvicar/terraform-provider-libvirt#308] opened 2018-06-16 11:09 UTC
#  Version Reports:

### Distro  version of host:
Ubuntu
``` openSUSE 42.2/ Centos7/ Ubuntu.. ```
Ubuntu 18.04
### Terraform Version Report
(Provided by running `terraform -v`.)
0.11.7
### Libvirt version
libvirtd (libvirt) 4.0.0
```virsh --version```

**Comment by MalloZup** [comment] 2018-07-02 10:23
@ayaseen  yop i thx but i fear we would need more info to reproduce it, like the tf files and logs

**Comment by ansemjo** [comment] 2018-08-02 14:49
I hit a smilar error just now when using a single `bridge = "..."` statement inside a `network_interface { }`.

```hcl
resource "libvirt_domain" "coreos" {
  # basics
  name   = "coreos-${count.index}"
  memory = "1024"
  vcpu   = 2

  disk {
    volume_id = "${libvirt_volume.coreos.*.id[count.index]}"
  }

  network_interface {
    bridge = "kvm-bridge"
  }

  boot_device {
    dev = ["hd", "network"]
  }

  # needs qemu >= 2.6
  coreos_ignition = "${libvirt_ignition.ignition.id}"
  count           = "${var.cluster_size}"
}
```

It crashed Terraform entirely:
```
panic: runtime error: invalid memory address or nil pointer dereference
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc518b7]
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: goroutine 75 [running]:
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.getDomainInterfacesFromNetworks(0x0, 0x0, 0xc420311048, 0x6, 0xc420311078, 0x3, 0xc420311080, 0xc4203110a8, 0x8, 0xc420318570, ...)
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:         /home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.4.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go:209 +0x157
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.domainGetIfacesInfo(0x7fa6080014f0, 0x0, 0x0, 0xc420311048, 0x6, 0xc420311078, 0x3, 0xc420311080, 0xc4203110a8, 0x8, ...)
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:         /home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.4.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go:167 +0x196
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.resourceLibvirtDomainRead(0xc420162e00, 0xe2d380, 0xc42031f220, 0x0, 0x0)
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:         /home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.4.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go:760 +0x1b63
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.resourceLibvirtDomainCreate(0xc420162e00, 0xe2d380, 0xc42031f220, 0x0, 0x0)
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:         /home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.4.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go:503 +0x11d7
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42009e540, 0xc420308640,0xc420313a40, 0xe2d380, 0xc42031f220, 0x1, 0xc42031a4e0, 0xc420462c00)
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:         /home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.4.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x364
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42009e850, 0xc4203085f0,0xc420308640, 0xc420313a40, 0x7fa62bbdd6c8, 0x0, 0x18)
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:         /home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.4.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4204189e0, 0xc4203139e0, 0xc4204a7970, 0x0, 0x0)
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:         /home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.4.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt: reflect.Value.call(0xc4200613e0, 0xc420426370, 0x13, 0x1018fc8, 0x4, 0xc420346f20, 0x3, 0x3, 0x0, 0x0, ...)
2018-08-02T16:25:55.360+0200 [DEBUG] plugin.terraform-provider-libvirt:         /usr/lib/golang/src/reflect/value.go:434 +0x905
2018-08-02T16:25:55.361+0200 [DEBUG] plugin.terraform-provider-libvirt: reflect.Value.Call(0xc4200613e0, 0xc420426370, 0x13, 0xc420367f20, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-08-02T16:25:55.361+0200 [DEBUG] plugin.terraform-provider-libvirt:         /usr/lib/golang/src/reflect/value.go:302 +0xa4
2018-08-02T16:25:55.361+0200 [DEBUG] plugin.terraform-provider-libvirt: net/rpc.(*service).call(0xc420499a00, 0xc420084140, 0xc4204221d8, 0xc420316080, 0xc420112d00, 0xe319c0, 0xc4203139e0, 0x16, 0xe31a00, 0xc4204a7970, ...)
2018-08-02T16:25:55.361+0200 [DEBUG] plugin.terraform-provider-libvirt:         /usr/lib/golang/src/net/rpc/server.go:381 +0x142
2018-08-02T16:25:55.361+0200 [DEBUG] plugin.terraform-provider-libvirt: created by net/rpc.(*Server).ServeCodec
2018-08-02T16:25:55.361+0200 [DEBUG] plugin.terraform-provider-libvirt:         /usr/lib/golang/src/net/rpc/server.go:475 +0x36b
2018/08/02 16:25:55 [TRACE] root: eval: *terraform.EvalWriteState
2018/08/02 16:25:55 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/08/02 16:25:55 [TRACE] root: eval: *terraform.EvalIf
2018/08/02 16:25:55 [TRACE] root: eval: *terraform.EvalWriteState
2018/08/02 16:25:55 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/08/02 16:25:55 [TRACE] root: eval: *terraform.EvalApplyPost
2018-08-02T16:25:55.365+0200 [DEBUG] plugin: plugin process exited: path=/home/ansemjo/.terraform.d/plugins/terraform-provider-libvirt
2018/08/02 16:25:55 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* libvirt_domain.coreos: unexpected EOF
2018/08/02 16:25:55 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* libvirt_domain.coreos: unexpected EOF
2018/08/02 16:25:55 [TRACE] [walkApply] Exiting eval tree: libvirt_domain.coreos
2018/08/02 16:25:55 [TRACE] dag/walk: upstream errored, not walking "provider.libvirt (close)"
2018/08/02 16:25:55 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/08/02 16:25:55 [TRACE] dag/walk: upstream errored, not walking "root"
2018/08/02 16:25:55 [TRACE] Preserving existing state lineage "202f52d1-e03a-651d-3c61-039f4658aef7"
2018/08/02 16:25:55 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-08-02T16:25:55.372+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-08-02T16:25:55.374+0200 [DEBUG] plugin: plugin process exited: path=/home/ansemjo/terraform-project/.terraform/plugins/linux_amd64/terraform-provider-ignition_v1.0.1_x4
```

Can't say for sure which version of the provider I was using though:

```
$ terraform -v
Terraform v0.11.7
+ provider.ignition v1.0.1
+ provider.libvirt (unversioned)
```

Updating the provider by compiling it from source seems to have fixed the problem. No more crashes so far ...

```
$ git -C ~/go/src/github.com/dmacvicar/terraform-provider-libvirt/ rev-parse HEAD
84823f8f34e184e31899b61710843a2b9af215c6
```

**Comment by MalloZup** [comment] 2018-08-20 19:15
reproducing with latest provider
```
* libvirt_volume.centos7_volume: Error while uploading source http://schnell.nue.suse.com/sumaform-images/centos7.qcow2: unexpected EOF
2018/08/20 20:08:36 [ERROR] root.base: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* libvirt_volume.centos7_volume: Error while uploading source http://schnell.nue.suse.com/sumaform-images/centos7.qcow2: unexpected EOF
```

**Comment by MalloZup** [comment] 2018-08-21 12:37
@ansemjo thx for your comment :+1: i"m working on it :sunflower:

**Comment by ansemjo** [comment] 2018-08-21 12:46
I'm happy if my comment helped finding a bug but I _think_ that you've hit a different issue than mine? As I said, after updating to master 18 days ago I had no more crashes for my usecase. It looks like my issue might have been fixed by 49e87713adc09eae69c175e2b1a458e7c59a1c6d or at least around that timeframe.

Either way, you're welcome. :)

**Comment by MalloZup** [comment] 2018-08-21 12:55
yop you are right :sunglasses:  , this are 2 diff issues, but ok the original one is about a ReaderIO your is on networking yop thx ! have a nice day

**Comment by MalloZup** [comment] 2018-08-21 14:47
after using more debug, found out that the EOF is coming from 
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/utils_volume.go#L159.

**Comment by MalloZup** [comment] 2018-08-22 10:46
@ayaseen do you have a TF file that you used for this? ( i can reproduce it not always with other env but is ok to have more just in case)tia

@dmacvicar i did some reaserch on this.

so we get an unEOF this mean that an EOF was encountered in the middle of reading a fixed-size block or data structure. 
I just checkout the HTTP part were we implement the io.Reader and this seems really fine to me.

My rough idea is more on the libvirt-api, namely on the upload call on libvirt, i think we have there the race condition  i will investigate and experiment more on it.

Afaik we have this issues since long-long time. We have it more visible using the latest sumaform with tf11 and latest problem , or i can reproduce more frequently this issue.

If you have any hint or suggestion feel free :rocket: :smile: :sunflower:

**Comment by MalloZup** [comment] 2018-08-23 08:01
@ayaseen it ended up that was not a bug from provider, but the image on the server were the pb.

curl 18
https://curl.haxx.se/libcurl/c/libcurl-errors.html

I just open a PR for improving the errmsg

**Closed** 2018-09-05 10:04 UTC
Labels: bug, waiting-review
