### ISSUE TITLE
Create 2 KVM libvirt networks failed

### ISSUE THREAD

**Issue by magsoftware** [dmacvicar/terraform-provider-libvirt#703] opened 2020-02-08 21:34 UTC
### Linux distribution

```
 Centos7
```

### Terraform version

```sh
Terraform v0.12.20
+ provider.libvirt (unversioned)
```

### Provider and libvirt versions

```sh
Compiled against library: libvirt 4.1.0
Using library: libvirt 4.5.0
Running hypervisor: QEMU 1.5.3
Running against daemon: 4.5.0
```
___

## Description of Issue/Question

It looks like it is not possible to define 2 networks.

### Setup

```
# Create a network for our VMs
resource "libvirt_network" "kube_network" {
  name = "k8s-net"
  mode = "nat"
  addresses = [ "10.0.1.0/24" ]
  dhcp {
    enabled = true
  }
  dns {
    enabled = true
    local_only = true
  }
}

#
# Output
#

output "kube_network" {
  value = libvirt_network.kube_network.name
}

# Create a network for our VMs
resource "libvirt_network" "ext_network" {
  name = "ext-net"
  mode = "nat"
  addresses = [ "10.10.1.0/24" ]
  dhcp {
    enabled = true
  }
  dns {
    enabled = true
    local_only = true
  }
}

#
# Output
#

output "ext_network" {
  value = libvirt_network.ext_network.name
}
```

### Steps to Reproduce Issue

```
# virsh net-list --all
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes

# terraform apply -auto-approve
libvirt_network.kube_network: Creating...
libvirt_network.ext_network: Creating...
libvirt_network.ext_network: Creation complete after 5s [id=278b4352-0843-4ff5-b737-05485d530851]

Error: Error clearing libvirt network: virError(Code=38, Domain=0, Message='error creating bridge interface virbr1: File exists')

  on network.tf line 2, in resource "libvirt_network" "kube_network":
   2: resource "libvirt_network" "kube_network" {


# virsh net-list --all
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 ext-net              active     no            yes
 k8s-net              inactive   no            yes
```
___
## Additional information:

SELinus in Permissive mode

If I create 2 different directories and split main.tf so that each main.tf contain only a single network definition than it works and 2 networks are created.

**Comment by mateuszbanasiewicz** [comment] 2020-02-23 15:30
Problem is connected with bridge interface which is created during creating network. 
As a workaround you can add to definiction of resource "libvirt_network" attribute "bridge".
Below my example:
```
resource "libvirt_network" "network_openshift4_data" {
  name      = "tf_openshift4_data"
  autostart = true
  mode      = "nat"
  bridge    = "tf_br80opendata"
  domain    = "edu.local"
  addresses = ["10.122.2.0/24"]
  dns {
    enabled = true
    forwarders {
      address = "192.168.1.199"
    }
  }
  dhcp {
    enabled = true
  }
}
```

**Comment by vmorris** [comment] 2020-05-09 20:56
Here's a reproduction of a similar problem but different error:

```hcl
resource "libvirt_network" "network_1" {
  name = "net1"
  domain = "net1.local"
  addresses = ["198.168.201.0/24"]
}

resource "libvirt_network" "network_2" {
  name = "net2"
  domain = "net2.local"
  addresses = ["198.168.202.0/24"]
}

```


```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # libvirt_network.network_1 will be created
  + resource "libvirt_network" "network_1" {
      + addresses = [
          + "198.168.201.0/24",
        ]
      + bridge    = (known after apply)
      + domain    = "net1.local"
      + id        = (known after apply)
      + mode      = "nat"
      + name      = "net1"
    }

  # libvirt_network.network_2 will be created
  + resource "libvirt_network" "network_2" {
      + addresses = [
          + "198.168.202.0/24",
        ]
      + bridge    = (known after apply)
      + domain    = "net2.local"
      + id        = (known after apply)
      + mode      = "nat"
      + name      = "net2"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

libvirt_network.network_2: Creating...
libvirt_network.network_1: Creating...
libvirt_network.network_2: Creation complete after 5s [id=04c0e7a2-d0af-4d64-9926-26372e0848a9]

Error: Error defining libvirt network: virError(Code=9, Domain=19, Message='operation failed: network 'net1' already exists with uuid 5ea3e9ac-c202-4c24-85cf-9a4bcfa23712') -   <network>
      <name>net1</name>
      <forward mode="nat"></forward>
      <bridge stp="on"></bridge>
      <domain name="net1.local"></domain>
      <dns enable="no"></dns>
      <ip address="198.168.201.1" family="ipv4" prefix="24">
          <dhcp>
              <range start="198.168.201.2" end="198.168.201.254"></range>
          </dhcp>
      </ip>
  </network>

  on network.tf line 1, in resource "libvirt_network" "network_1":
   1: resource "libvirt_network" "network_1" {

```

**Comment by vmorris** [comment] 2020-05-09 23:56
I agree, the networks are being created in parallel with the same bridge name and whichever one starts first gets to come up okay and any others will fail.

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_network.go#L383

Would it be okay if we create a unique bridge name based on the `networkDef.Name` instead of letting libvirt assign one?

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/network.go#L137

**Comment by MalloZup** [comment] 2020-05-17 09:29
@magsoftware thx for issue, you can test patch from @vmorris on master merged

**Comment by MalloZup** [comment] 2020-05-17 09:49
Closing this issue, but feel free to reopen if the master fix doens't fix

**Comment by MalloZup** [comment] 2020-09-26 12:24
re-opening this as discussed since this is not a valid fix

**Comment by MalloZup** [comment] 2020-09-26 12:56
I could not reproduce it on my openSUSE leap Linux machine.

See.

```
/usr/bin/terraform-provider-libvirt --version
/usr/bin/terraform-provider-libvirt a5a527f089b775f67c7d1664722ab7ec5aa274d0-dirty
Compiled against library: libvirt 6.0.0
Using library: libvirt 6.0.0
Running hypervisor: QEMU 4.2.1
Running against daemon: 6.0.0
```

```  Enter a value: yes

libvirt_network.kube_network: Creating...
libvirt_network.ext_network: Creating...
libvirt_network.ext_network: Creation complete after 5s [id=ea4bde69-7628-4e26-9299-270c6ae6c026]
libvirt_network.kube_network: Creation complete after 5s [id=830e44a7-827a-4e7b-8e65-deb381f6dd22]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

```
dmaiocchi@linux-buft:/tmp/net-tf> virsh net-list --all
 Name            State      Autostart   Persistent
----------------------------------------------------
 default         active     yes         yes
 ext-net         active     no          yes
 hqmtobjeev      inactive   no          yes
 k8s-net         active     no          yes
 local-private   active     yes         yes
 local-public    active     yes         yes

```






@magsoftware  can you try to update your libvirt version and see if you can reproduce?

**Comment by dmacvicar** [comment] 2020-09-26 14:01
I can reproduce it on libvirt-6.7.0 on Tumbleweed.

**Closed** 2020-09-30 19:16 UTC
