### ISSUE TITLE
main.go :   cannot use "libvirt".Provider in field value "plugin".ProviderFunc

### ISSUE THREAD

**Issue by bluefishforsale** [dmacvicar/terraform-provider-libvirt#206] opened 2017-10-27 04:59 UTC
# host info
Name: libvirt
Version: 3.2.0

go version
go version go1.9.1 linux/amd64

OS: centos:7 in docker

$ export GOPATH="$(pwd)"
$ export PATH="/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/go/bin"
$ export PATH="${GOROOT}:${PATH}"
$ export PKG_CONFIG_PATH="$(pwd)/libvirt"

## ENVS
ARCH=amd64
BASH_VERSION='4.2.46(2)-release'
GITLAB_CI=true
GITLAB_USER_ID=2
GOPATH=/builds/xxxxxxxx/terraform_libvirt
HOSTNAME=runner-51991791-project-9-concurrent-0
HOSTTYPE=x86_64
IFS=$' \t\n'
MACHTYPE=x86_64-redhat-linux-gnu
OSTYPE=linux-gnu
PATH=:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/go/bin
PIPESTATUS=([0]="0")
PKG_CONFIG_PATH=/builds/xxxxxxxx/terraform_libvirt/libvirt
PWD=/builds/xxxxxxxx/terraform_libvirt
SHELL=/bin/bash
SHELLOPTS=braceexpand:errexit:hashall:interactive-comments:pipefail
SHLVL=1
TERM=dumb
UID=0
VERSION=1.9.1
container=docker

# build attempt
$ go build main.go

./main.go:12:15: cannot use "github.com/dmacvicar/terraform-provider-libvirt/libvirt".Provider (type func() "github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value
  ERROR: Job failed: exit code 1

**Comment by monstermunchkin** [comment] 2017-10-27 09:20
Are you experiencing this on the `master` branch? Did you possibly run `glide` beforehand?

**Comment by monstermunchkin** [comment] 2017-10-27 09:50
I'm unable to reproduce this in a centos:7 docker container.

Is this repo located at `${GOPATH}/src/github.com/dmacvicar/terraform-provider-libvirt`? Do you get the same error when running `go get github.com/dmacvicar/terraform-provider-libvirt`?

**Comment by bluefishforsale** [comment] 2017-10-31 18:07
You are correct, I had run a glide up at some point. A fresh pull of the master changed the operation of go build main.go


however, now I believe I have some GO ENV set incorrectly.


$ export GOPATH="$(pwd)"
$ export PATH="/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/go/bin"
$ export PATH="${GOROOT}:${PATH}"
$ export XC_OS=linux XC_ARCH=amd64 make bin
$ go build main.go
main.go:4:2: cannot find package "github.com/dmacvicar/terraform-provider-libvirt/libvirt" in any of:
	/usr/local/go/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt (from $GOROOT)
	/builds/user/terraform_libvirt/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt (from $GOPATH)
main.go:5:2: cannot find package "github.com/hashicorp/terraform/plugin" in any of:
	/usr/local/go/src/github.com/hashicorp/terraform/plugin (from $GOROOT)
	/builds/user/terraform_libvirt/src/github.com/hashicorp/terraform/plugin (from $GOPATH)


Any advice?

**Comment by MalloZup** [comment] 2017-11-02 07:52
@bluefishforsale You are not exporting  GOPATH to PATH that is why go complain not find, looking at your snippet. Hope it helps

**Comment by MalloZup** [comment] 2017-11-03 19:11
@bluefishforsale  i had the same issue on a machine.(debian)

What you have there is an issue that glide **could not install libvirt pkg** (golang pkg)

So try this:
1. Install libvirt-devel pkg
2. go get github.com/libvirt/libvirt-go
3. go build  should work

Let me know if it works.

**Comment by bluefishforsale** [comment] 2017-11-04 20:03
little more info on my build environment
This is in the Dockerfile i'm using for the environment (in addition to much more)
`FROM centos:7 
RUN yum install -y git libvirt-lib libvirt-devel which qemu-kvm`

**Comment by bluefishforsale** [comment] 2017-11-05 03:56
current situation

`$ go get github.com/hashicorp/terraform/plugin`
`$ go get github.com/libvirt/libvirt-go`
`$ go get github.com/dmacvicar/terraform-provider-libvirt`
`$ go build main.go`
`# command-line-arguments`
`./main.go:12:15: cannot use "github.com/dmacvicar/terraform-provider-libvirt/libvirt".Provider (type func() "github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value`

**Comment by MalloZup** [comment] 2017-11-05 16:33
@bluefishforsale 

you need to be in the src of the pkg for building.

´´´console

cd $GOPATH/src/github.com/dmacvicar/terraform-provider-libvirt/
go build
´´´´

**Comment by bluefishforsale** [comment] 2017-11-05 16:53
@MalloZup thanks, this is my first time building a golang project at all, let alone someone elses. Lots of new moving parts here for me.

I appreciate the hand-holding. Hopefully i'll get a lot of value from this and be able to pay it forward for others needing help.

**Comment by MalloZup** [comment] 2017-11-05 16:59
@bluefishforsale yop no problem, there is always a fist time :+1:
Feel free to improve also the documentation with some PRs if you feel that is lacking on doc.

**Comment by MalloZup** [comment] 2017-11-07 13:27
@bluefishforsale  if it fixed the issue, feel free to close it !  feel free to open others issue or propose whatever you wish and maybe we can hack togheter in golang on this on other proj ! have fun

**Closed** 2017-11-07 16:54 UTC
Labels: needinfo

**Comment by kjenney** [comment] 2018-03-21 06:05
I found this useful in the build and figured I'd share a little:

```
FROM golang
RUN apt-get update && apt-get -y install libvirt-dev libvirt-daemon qemu-kvm git
RUN go get github.com/hashicorp/terraform/plugin
RUN go get github.com/libvirt/libvirt-go
RUN go get github.com/dmacvicar/terraform-provider-libvirt
WORKDIR $GOPATH/src/github.com/dmacvicar/terraform-provider-libvirt/
RUN echo "go build main.go" > /script.sh
RUN echo "cp /go/bin/terraform-provider-libvirt /binary" >> /script.sh
RUN chmod +x /script.sh
CMD /script.sh
```

Build with:
```
docker build -t terraform-libvirt .
docker run -it --rm -v $PWD/bin:/binary terraform-libvirt
```
