### ISSUE TITLE
Crash on apply of libvirt_domain

### ISSUE THREAD

**Issue by fvhovell** [dmacvicar/terraform-provider-libvirt#120] opened 2017-03-26 09:38 UTC
#  Version Reports:

### Distro  version of host:

``` Ubuntu 16.04.2 ```

### Terraform Version Report

```Terraform v0.9.1```

### Libvirt version

```1.3.1```

### terraform-provider-libvirt plugin version (git-hash)

```
commit a07e21b74726d9ce443ac9332417c169b2ccd708
Author: Eamonn O'Toole <eamonn.otoole@hpe.com>
Date:   Thu Mar 16 16:12:22 2017 +0000
```

___
# Description of Issue/Question

On applying the libvirt_domain config terraform crashes (but the VM is actually running fine, including networking):
```
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: panic: runtime error: invalid memory address or nil pointer dereference
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x52c6ad]
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: goroutine 64 [running]:
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/libvirt-go.(*VirDomain).ListAllInterfaceAddresses(0xc420273370, 0x0, 0x1, 0xc4203c43f0, 0x0, 0x0, 0xb694d0)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /home/frederik/src/_go/src/github.com/dmacvicar/libvirt-go/domain.go:767 +0x35d
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.getDomainInterfaces(0xc420273370, 0x44, 0xc42039e230, 0x1, 0x1, 0x1)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /home/frederik/src/_go/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go:983 +0x113
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.waitForNetworkAddresses(0xc4202803c0, 0x1, 0x1, 0x7ff20c001220, 0x1, 0x10b70e0)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /home/frederik/src/_go/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go:909 +0x279
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.resourceLibvirtDomainCreate(0xc42035a540, 0xa28a40, 0xc4202dab58, 0x0, 0x0)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /home/frederik/src/_go/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go:485 +0x385e
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4202ce840, 0xc420266960, 0xc4203846c0, 0xa28a40, 0xc4202dab58, 0x1, 0x28, 0xc420379b90)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /home/frederik/src/_go/src/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x48d
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42025bab0, 0xc420266910, 0xc420266960, 0xc4203846c0, 0x7ff23d8422c0, 0x0, 0x0)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /home/frederik/src/_go/src/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4203067c0, 0xc420384140, 0xc420381610, 0x0, 0x0)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /home/frederik/src/_go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: reflect.Value.call(0xc4202563c0, 0xc420272840, 0x13, 0xb3fe76, 0x4, 0xc420265f20, 0x3, 0x3, 0xb694d0, 0xc420207ee8, ...)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /usr/local/go/src/reflect/value.go:434 +0x91f
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: reflect.Value.Call(0xc4202563c0, 0xc420272840, 0x13, 0xc420207f20, 0x3, 0x3, 0xc420207f0c, 0x180001, 0x500000000)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /usr/local/go/src/reflect/value.go:302 +0xa4
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: net/rpc.(*service).call(0xc4203013c0, 0xc420301380, 0xc42030a9c0, 0xc420308080, 0xc42034c480, 0xa29a40, 0xc420384140, 0x16, 0xa29a80, 0xc420381610, ...)
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /usr/local/go/src/net/rpc/server.go:387 +0x144
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt: created by net/rpc.(*Server).ServeCodec
2017/03/25 18:49:30 [DEBUG] plugin: terraform-provider-libvirt:         /usr/local/go/src/net/rpc/server.go:481 +0x404
2017/03/25 18:49:30 [DEBUG] root: eval: *terraform.EvalWriteState
2017/03/25 18:49:30 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/03/25 18:49:30 [DEBUG] root: eval: *terraform.EvalIf
2017/03/25 18:49:30 [DEBUG] root: eval: *terraform.EvalWriteState
2017/03/25 18:49:30 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/03/25 18:49:30 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/03/25 18:49:30 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* libvirt_domain.test01: unexpected EOF
2017/03/25 18:49:30 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* libvirt_domain.test01: unexpected EOF
2017/03/25 18:49:30 [TRACE] [walkApply] Exiting eval tree: libvirt_domain.test01
2017/03/25 18:49:30 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
```

### Setup

```
provider "libvirt" {
    uri = "qemu:///system"
}

resource "libvirt_volume" "mydisk" {
  name             = "terraform-test1.img"
  pool             = "default"
  base_volume_name = "centos-7.3_vagrant_box_image_0.img"
}

resource "libvirt_domain" "test01" {
  name    = "terraform_test01"
  vcpu    = 2
  memory  = 1024
  running = "false"

  disk {
    volume_id = "${libvirt_volume.mydisk.id}"
    scsi      = "yes"
  }

  network_interface {
    network_name   = "default"
    hostname       = "test1"
    mac            = "AA:BB:CC:11:22:22"
    wait_for_lease = 1
  }
}
```

### Steps to Reproduce Issue

```
terraform plan
terraform apply
```

See attached [crash log](https://github.com/dmacvicar/terraform-provider-libvirt/files/870658/crash.log.txt).
___
# Additional Infos:

Apparmor is disabled, I do have a firewall (ufw) enabled on both the host, but this is working fine as I can actually login using SSH to the newly started VM and see that it has networking operational just fine.

**Comment by monstermunchkin** [comment] 2017-08-07 15:52
I cannot reproduce this bug on `master`, and the log shows that the problem originates from `libvirt-go` so this might not be fixable by us. However, it might be related to libvirt/libvirt-go#15 which has been fixed upstream.

I'm closing this since it probably has been fixed already. Feel free to reopen this issue if it occurs again.

**Closed by monstermunchkin** 2017-08-07 15:52 UTC
Labels: bug
