### ISSUE TITLE
volume source does not accept dots in file name.

### ISSUE THREAD

**Issue by fisabelle** [dmacvicar/terraform-provider-libvirt#13] opened 2016-04-21 19:58 UTC
I don't know if the problem is in qemu, but using:

// Than you may define a template, this file is not modified
resource "libvirt_volume" "template7" {
  pool = "ram"
  name = "template7"
  source = "http://localhost:8000/centos7.std.base"
}

it gave me:

qemu-img: /home/vmstore/ramdisk/centos7vm1_mydisk: Could not open backing file: Could not open '/home/vmstore/ramdisk/centos7.base': No such file or directory

some part of the filename was stripped out.

**Comment by MalloZup** [comment] 2017-03-13 20:47
I tried it out to reproduce this bug, without success.
For me the bug/Issue is **invalid**

This is not an issue on dot on names.

All tests i did worked fine, with dots.

First i did:
``` console
provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_volume" "opensuse_leap" {
  name = "opensuse_leap"
  source = "/image/centos7.std.base"
}

resource "libvirt_volume" "volume" {
  name = "volume.${count.index}"
  base_volume_id = "${libvirt_volume.opensuse_leap.id}"
  count = 1
}

resource "libvirt_domain" "domain" {
  name = "domain.${count.index}"
  disk {
       volume_id = "${element(libvirt_volume.volume.*.id, count.index)}"
  }
  count = 1
}

```


then:

```console
provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_volume" "opensuse_leap" {
  name = "opensuse_leap"
  source = "http://localhost:8000/centos7.std.base"
}

resource "libvirt_volume" "volume" {
  name = "volume.${count.index}"
  base_volume_id = "${libvirt_volume.opensuse_leap.id}"
  count = 1
}

resource "libvirt_domain" "domain" {
  name = "domain.${count.index}"
  disk {
       volume_id = "${element(libvirt_volume.volume.*.id, count.index)}"
  }
  count = 1
```

For me, after researching looks like a permission issue:

googling simple the err-code:
https://forum.opennebula.org/t/could-not-open-backing-file/1504

At least is not a dot issue on name files.

Imho we can close this @inercia , @flavio

**Closed** 2017-03-15 13:54 UTC
Labels: bug
