### ISSUE TITLE
Provider not found in registry

### ISSUE THREAD

**Issue by ulm0** [dmacvicar/terraform-provider-libvirt#798] opened 2020-10-28 15:57 UTC
Looks like the provider is not available in the registry 

### Linux distribution

``` Ubuntu```

### Terraform version

```sh
terraform -v
Terraform v0.13.5
```

### Provider and libvirt versions

```sh
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
dmacvicar/libvirt: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/dmacvicar/libvirt
```

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [ ] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [x] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

### Setup

```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    libvirt = {
      source  = "dmacvicar/libvirt"
      version = "0.6.2"
    }
  }
}
```

### Steps to Reproduce Issue

Try to use the provider

```sh
$ terraform init
...
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
dmacvicar/libvirt: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/dmacvicar/libvirt
```

___
## Additional information:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?

None of the above is enabled, plain connection to internet

**Comment by MalloZup** [comment] 2020-10-28 15:59
@ulm0  thx for issue.
I'm closing this because it is a duplicate of https://github.com/dmacvicar/terraform-provider-libvirt/issues/747

also check the documentation https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/docs/migration-13.md

**Comment by MalloZup** [comment] 2020-10-28 15:59
for any info feel free to ping me :+1:

**Closed by MalloZup** 2020-10-28 15:59 UTC
